#!/usr/bin/env python3
r"""Calculemus: the end-to-end universal reasoning machine.

    claim (.uc) -> IR + fingerprint -> proof search -> Lean synthesis
        -> kernel verification -> append-only adjudication ledger

Nothing is asserted by narrative. A claim is only reported as `kernel-proven`
when the Lean 4 kernel has accepted the synthesized theorem; claims the search
engine cannot close are recorded as `open`, and the ledger keeps both kinds
without shame or embellishment - the ledger wins over narrative.

Usage:
    python3 calculemus.py examples/monadology_argument.uc [more.uc ...]
        [--dry-run] [--install] [--registry adjudications.jsonl]

--dry-run     skip kernel verification (verdict stays `derived`, never
              `kernel-proven`); used in CI jobs without a Lean toolchain.
--install     write kernel-verified theorems into Leibniz/Generated/ and import
              them from Leibniz.lean, so `lake build` re-checks them forever.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import time
import unicodedata
from pathlib import Path

from proof_engine import _relation, search
from ucalculus import Claim, compile_claim, parse

ROOT = Path(__file__).resolve().parent
GENERATED_DIR = ROOT / "Leibniz" / "Generated"
LEAN_TOOLCHAIN_TIMEOUT_S = 1800

VERDICTS = ("kernel-proven", "derived", "open", "under-specified", "kernel-rejected")


# --------------------------------------------------------------------------
# identifiers: natural-language terms -> safe Lean identifiers
# --------------------------------------------------------------------------

def _fold(term: str) -> str:
    text = unicodedata.normalize("NFKD", term)
    text = "".join(c for c in text if not unicodedata.combining(c))
    return re.sub(r"[^A-Za-z0-9_]+", "_", text).strip("_")


def lean_ident(term: str) -> str:
    """`contingent event` -> `contingentEvent` (a variable name)."""
    words = [w for w in _fold(term).split("_") if w]
    if not words:
        raise ValueError(f"term {term!r} has no usable identifier")
    return words[0].lower() + "".join(w[:1].upper() + w[1:] for w in words[1:])


def pascal(name: str) -> str:
    """`SufficientReason` -> `SufficientReason` (a theorem/module name)."""
    words = [w for w in _fold(name).split("_") if w]
    return "".join(w[:1].upper() + w[1:] for w in words)


# --------------------------------------------------------------------------
# Lean synthesis: a real theorem, no sorry, no axioms beyond Lean's standard three
# --------------------------------------------------------------------------

HEADER = """\
/-
  Machine-generated by the Calculemus proof engine. DO NOT EDIT BY HAND.

  Claim source       : {example}
  Philosophical claim: {name}
  Source citation    : {citation}
  IR fingerprint     : {fingerprint}
  Proof rule         : {rule}

  The natural-language relation terms are abstracted to variables of an
  arbitrary preordered type; the theorem records the exact logical form
  of the philosophical inference. The kernel checks the form, not the
  philosophy - that division of labor is the whole point of Calculemus.
-/

import Mathlib

namespace Leibniz.Generated

"""


def synthesize(claim: Claim, result, source_file: str = "") -> tuple[str, str] | None:
    """Return (lean_source, theorem_name) when the search engine closed the goal."""
    if result.outcome != "proved" or not result.steps:
        return None
    step = result.steps[0]
    conclusion = _relation(claim.conclusion)
    if conclusion is None:
        return None
    left, op, right = conclusion

    def premise_index(text: str) -> int:
        for i, p in enumerate(claim.premises, 1):
            if p.text == text:
                return i
        raise ValueError(f"proof step cites unknown premise: {text}")

    if step.rule == "direct":
        h = premise_index(step.from_premises[0])
        ident_left, ident_right = lean_ident(left), lean_ident(right)
        body = f"h{h}"
        relation_decl = f"{ident_left} {ident_right} : \u03b1"
        hyps = f"(h{h} : {ident_left} \u2265 {ident_right})"
        goal = f"{ident_left} \u2265 {ident_right}"
    elif step.rule == "transitivity":
        edge_ab, edge_bc = step.from_premises
        h_ab, h_bc = premise_index(edge_ab), premise_index(edge_bc)
        rel_ab, rel_bc = _relation(edge_ab), _relation(edge_bc)
        if not (rel_ab and rel_bc and rel_ab[2] == rel_bc[0]):
            raise ValueError("transitivity step does not share a middle term")
        a, mid, c = lean_ident(left), lean_ident(rel_ab[2]), lean_ident(right)
        body = f"le_trans h{h_bc} h{h_ab}"
        relation_decl = f"{a} {mid} {c} : \u03b1"
        hyps = f"(h{h_ab} : {a} \u2265 {mid})\n    (h{h_bc} : {mid} \u2265 {c})"
        goal = f"{a} \u2265 {c}"
    else:
        return None

    theorem_name = f"{claim.name[0].lower() + claim.name[1:]}_{step.rule}"
    citation = claim.source or "(no source clause)"
    source = HEADER.format(
        example=source_file or "(unknown)", name=claim.name, citation=citation,
        fingerprint=compile_claim(claim).fingerprint, rule=step.rule)
    source += (
        f"theorem {theorem_name} {{\u03b1 : Type*}} [Preorder \u03b1]\n"
        f"    ({relation_decl})\n"
        f"    {hyps} :\n"
        f"    {goal} :=\n"
        f"  {body}\n"
        f"\nend Leibniz.Generated\n")
    return source, theorem_name


# --------------------------------------------------------------------------
# kernel verification
# --------------------------------------------------------------------------

def kernel_verify(lean_source: str, repo_root: Path = ROOT,
                  timeout: int = LEAN_TOOLCHAIN_TIMEOUT_S) -> tuple[bool, str, float]:
    """Check the synthesized theorem with the real Lean 4 kernel (`lake env lean`)."""
    scratch = repo_root / ".lake" / "calculemus-check.lean"
    scratch.parent.mkdir(exist_ok=True)
    scratch.write_text(lean_source, encoding="utf-8")
    start = time.monotonic()
    proc = subprocess.run(["lake", "env", "lean", str(scratch)],
                          cwd=repo_root, capture_output=True, text=True, timeout=timeout)
    duration = time.monotonic() - start
    scratch.unlink(missing_ok=True)
    return proc.returncode == 0, (proc.stdout + proc.stderr).strip(), duration


# --------------------------------------------------------------------------
# installation into the Lean library
# --------------------------------------------------------------------------

README_GENERATED = """\
# Generated theorems (machine output)

Every file in this directory is machine-generated by `calculemus.py --install`
from a Universal Calculus claim in `examples/`, and is re-checked by the Lean 4
kernel on every `lake build`. Do not edit by hand - regenerate instead:

    python3 calculemus.py examples/monadology_argument.uc --install

The `adjudications.jsonl` ledger at the repository root records when and how
each theorem was derived and verified. The ledger wins over narrative.
"""


def install(lean_source: str, claim_name: str, repo_root: Path = ROOT) -> Path:
    """Write the theorem into Leibniz/Generated/ and import it from Leibniz.lean."""
    module = pascal(claim_name)
    generated = repo_root / "Leibniz" / "Generated"
    generated.mkdir(parents=True, exist_ok=True)
    target = generated / f"{module}.lean"
    target.write_text(lean_source, encoding="utf-8")
    (generated / "README.md").write_text(README_GENERATED, encoding="utf-8")

    umbrella = repo_root / "Leibniz.lean"
    if not umbrella.exists():
        return target
    text = umbrella.read_text(encoding="utf-8")
    import_line = f"import Leibniz.Generated.{module}"
    if import_line not in text:
        anchor = "import Leibniz.OpenProblems"
        text = text.replace(anchor, anchor + "\n" + import_line)
        umbrella.write_text(text, encoding="utf-8")
    return target


# --------------------------------------------------------------------------
# the pipeline
# --------------------------------------------------------------------------

def process(path: Path, dry_run: bool, do_install: bool, registry: Path) -> dict:
    claim = parse(path.read_text(encoding="utf-8"))
    ir = compile_claim(claim)
    result = search(claim)
    record = {
        "claim": claim.name,
        "source_file": str(path),
        "citation": claim.source,
        "fingerprint": ir.fingerprint,
        "search_outcome": result.outcome,
        "rule": result.steps[0].rule if result.steps else None,
    }

    synthesis = synthesize(claim, result, str(path))
    if synthesis is None:
        record.update(verdict="open" if result.outcome == "open" else "under-specified",
                      kernel_verified=False, explanation=result.explanation)
    elif dry_run:
        record.update(verdict="derived", kernel_verified=False,
                      explanation="proof search closed the goal; kernel check skipped (--dry-run)")
    else:
        source, theorem = synthesis
        ok, output, duration = kernel_verify(source)
        record.update(
            verdict="kernel-proven" if ok else "kernel-rejected",
            theorem=f"Leibniz.Generated.{theorem}",
            lean_sha256=hashlib.sha256(source.encode()).hexdigest(),
            kernel_verified=ok, kernel_duration_s=round(duration, 2),
            kernel_output=output[:400] if not ok else "")
        if ok and do_install:
            record["installed"] = str(install(source, claim.name).relative_to(ROOT))
        if not ok:
            print(f"KERNEL REJECTED {claim.name}:\n{output}", file=sys.stderr)

    record["timestamp"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    with registry.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False) + "\n")
    return record


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("claims", type=Path, nargs="+", help="Universal Calculus claim files (.uc)")
    parser.add_argument("--dry-run", action="store_true",
                        help="skip Lean kernel verification (verdict stays `derived`)")
    parser.add_argument("--install", action="store_true",
                        help="install kernel-verified theorems into Leibniz/Generated/")
    parser.add_argument("--registry", type=Path, default=ROOT / "adjudications.jsonl",
                        help="append-only adjudication ledger (JSONL)")
    args = parser.parse_args(argv)

    if not args.dry_run and subprocess.run(["which", "lake"],
                                           capture_output=True).returncode:
        print("warning: no lake toolchain found; falling back to --dry-run", file=sys.stderr)
        args.dry_run = True

    records = [process(p, args.dry_run, args.install, args.registry) for p in args.claims]
    for r in records:
        print(f"{r['claim']:24} {r['search_outcome']:14} -> {r['verdict']}")
    rejected = [r for r in records if r["verdict"] == "kernel-rejected"]
    return 1 if rejected else 0


if __name__ == "__main__":
    raise SystemExit(main())
